### ISSUE TITLE
Invalid wheel name (NekoMimi.whl)

### ISSUE THREAD

**Issue by NekoMimiOfficial** [FroscoInnovativeTechnologies/VitaDockLite#4]
Yeah I don't know how I messed this up very badly but I'll just have to rename the wheel back to it's original name (^ ^;)

**Comment by Girotin** [comment]
Any news on this? I'm having trouble installing it on Zorin OS :/

Currently trying everything (I'm new to linux and general programming)

Edit: WAIT!!! I MANAGED TO INSTALL IT!!! Renamed it to "NekoMimi-1.0.0-py3-none-any.whl"

Am currently troubleshooting it to make it work, managed to open the VDockLite file, but it seems to be having troubles with other filepaths (Idk if I messed up the install or something is really missing)

I'll keep updating here if I find something new

**Comment by NekoMimiOfficial** [comment]
Resolved on latest commit

**Comment by Girotin** [comment]
That was fast :0
